on:
  push:
    branches:
      - main
name: Build Gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: deploy
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GH_PAT }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
          skip-publish: false
